TRANSLATIONS = {
    "English": {
        "window_title": "PDF and PPTX to Word Summary",
        "select_files": "Select PDF and PPTX Files",
        "generate": "Generate Summary",
        "interface_lang": "Interface Language:",
        "output_lang": "Output Summary Language:",
        "success_message": "Summary generated successfully!",
        "selected_files": "Selected files:",
        "output_format": "Output Format:",
        "move_up": "Move Up",
        "move_down": "Move Down",
        "remove": "Remove",
        "content_options": "Content Options:",
        "include_images": "Include Images"
    },
    "Français": {
        "window_title": "Résumé PDF et PPTX vers Word",
        "select_files": "Sélectionner les fichiers PDF et PPTX",
        "generate": "Générer le résumé",
        "interface_lang": "Langue de l'interface:",
        "output_lang": "Langue du résumé:",
        "success_message": "Résumé généré avec succès!",
        "selected_files": "Fichiers sélectionnés:",
        "output_format": "Format de sortie:",
        "move_up": "Monter",
        "move_down": "Descendre",
        "remove": "Supprimer",
        "content_options": "Options de contenu:",
        "include_images": "Inclure les images"
    },
    "Italiano": {
        "window_title": "Riassunto PDF e PPTX in Word",
        "select_files": "Seleziona file PDF e PPTX",
        "generate": "Genera riassunto",
        "interface_lang": "Lingua dell'interfaccia:",
        "output_lang": "Lingua del riassunto:",
        "success_message": "Riassunto generato con successo!",
        "selected_files": "File selezionati:",
        "output_format": "Formato di output:",
        "move_up": "Sposta su",
        "move_down": "Sposta giù",
        "remove": "Rimuovi",
        "content_options": "Opzioni di contenuto:",
        "include_images": "Includi immagini"
    },
    "Español": {
        "window_title": "Resumen de PDF y PPTX a Word",
        "select_files": "Seleccionar archivos PDF y PPTX",
        "generate": "Generar resumen",
        "interface_lang": "Idioma de la interfaz:",
        "output_lang": "Idioma del resumen:",
        "success_message": "¡Resumen generado con éxito!",
        "selected_files": "Archivos seleccionados:",
        "output_format": "Formato de salida:",
        "move_up": "Subir",
        "move_down": "Bajar",
        "remove": "Eliminar",
        "content_options": "Opciones de contenido:",
        "include_images": "Incluir imágenes"
    }
}